### ISSUE TITLE
Sbcl not installed

### ISSUE THREAD

**Issue by newmentos** [smashedtoatoms/asdf-sbcl#6]
I have tried:
`asdf install sbcl 2.0.3`
In the end of the compilation this message:
```
WARNING! Some of the contrib modules did not build successfully or pass
their self-tests. Failed contribs:"
  sb-posix
```
`asdf global sbcl 2.0.3`
`version 2.0.3 is not installed for sbcl`
On [stackoverflow.com](https://stackoverflow.com/questions/21288143/need-help-running-thread-sbcl) recommended use flag `--with-sb-thread` for compile from source.
My system: `uname -srmo`
`Linux 5.5.16-1-ck-ivybridge x86_64 GNU/Linux`

**Comment by smashedtoatoms** [comment]
Cool.  I had put off writing the code to allow compiler flags to be passed in because I was just trying to get this working.  Let me add the logic to handle compiler flags really quick so you can experiment with those to get what you need.

**Comment by smashedtoatoms** [comment]
Ok, 1b2ff045efcd54e239414f37e6f305ef3fb94d63 should have fixed this.  When you get a chance, can you try installing with: `SBCL_CONFIGURE_OPTIONS="--with-sb-core-compression --with-sb-thread" asdf install sbcl 2.0.3` and let me know if it works?

**Comment by newmentos** [comment]
Skips failing tests SB-POSIX-TESTS::STAT.2, SB-POSIX-TESTS::STAT.4 for install sbcl 2.0.03 from source.
```
--- contrib/sb-posix/posix-tests.lisp	2020-03-28 23:58:29.000000000 +0300
+++ contrib/sb-posix/posix-tests.lisp.my	2020-04-12 09:27:00.600042007 +0300
@@ -235,7 +235,7 @@
     (logand mode (logior sb-posix::s-iread sb-posix::s-iwrite sb-posix::s-iexec)))
   #.(logior sb-posix::s-iread sb-posix::s-iwrite sb-posix::s-iexec))
 
-#-(or (and darwin x86) win32)
+#-(or (and darwin x86) win32 linux)
 (deftest stat.2
   (let* ((stat (sb-posix:stat "/"))
          (mode (sb-posix::stat-mode stat)))
@@ -256,7 +256,7 @@
     (< (- atime unix-now) 10))
   t)
 
-#-(or (and darwin x86) win32)
+#-(or (and darwin x86) win32 linux)
 (deftest stat.4
   (let* ((stat (sb-posix:stat (make-pathname :directory '(:absolute :up))))
          (mode (sb-posix::stat-mode stat)))

```
Made by analogy from this [bugs.gentoo.org](https://bugs.gentoo.org/attachment.cgi?id=377704&action=diff)

**Comment by smashedtoatoms** [comment]
So did that complete the install?

**Comment by newmentos** [comment]
> So did that complete the install?

Yes, but I did not check how the transfer of compilation parameters works, since that was not this problem. Compilation fifnished when i skip failing tests.

**Comment by smashedtoatoms** [comment]
Ahh, ok, gotcha.  Well, I had put off adding that until someone needed it, so I'm glad I at least got to check that off.  It works on my box. ;)
